---
standard:
  left:
    rows: ["a", "b", "c", "d"]
    columns: ["1", "2", "3", "4"]
    void_places:
    - ["a", "1"]
  middle:
    rows: ["a", "b", "c", "d"]
    columns: ["5", "6", "7", "8"]
    void_places: []
  right:
    rows: ["a", "b", "c", "d"]
    columns: ["9", "10", "11", "12"]
    void_places:
    - ["a", "12"]
small:
  left:
    rows: ["a", "b"]
    columns: [ "1", "2"]
    void_places:
    - ["a", "1"]
  middle:
    rows: ["a", "b"]
    columns: ["3", "4"]
    void_places: []
  right:
    rows: ["a", "b"]
    columns: ["5", "6"]
    void_places:
    - ["a", "6"]

enorme:
  middle:
    rows: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q"]
    columns: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]
    void_places: []
